[2021-09-23 22:52:02,492] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-09-22T00:00:00+00:00 [queued]>
[2021-09-23 22:52:02,497] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-09-22T00:00:00+00:00 [queued]>
[2021-09-23 22:52:02,498] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-09-23 22:52:02,498] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-09-23 22:52:02,498] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-09-23 22:52:02,520] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-09-22T00:00:00+00:00
[2021-09-23 22:52:02,522] {standard_task_runner.py:52} INFO - Started process 3619 to run task
[2021-09-23 22:52:02,528] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-09-22T00:00:00+00:00', '--job-id', '73', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprr0t1t73', '--error-file', '/tmp/tmphwzivbkx']
[2021-09-23 22:52:02,528] {standard_task_runner.py:77} INFO - Job 73: Subtask is_api_available
[2021-09-23 22:52:02,617] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-09-22T00:00:00+00:00 [running]> on host airflowvm
[2021-09-23 22:52:02,891] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-09-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-22T00:00:00+00:00
[2021-09-23 22:52:02,891] {http.py:101} INFO - Poking: api/
[2021-09-23 22:52:02,896] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-09-23 22:52:02,896] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-09-23 22:52:03,385] {base.py:243} INFO - Success criteria met. Exiting.
[2021-09-23 22:52:03,390] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210922T000000, start_date=20210923T225202, end_date=20210923T225203
[2021-09-23 22:52:03,416] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-09-23 22:52:03,432] {local_task_job.py:151} INFO - Task exited with return code 0
